### ISSUE TITLE
Aeson 0.11 migration

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#109]
I think this has the same behavior as 0.9, but this is where they're headed long-term.

Options:

1. Roll back to 0.9 since the semantics are the same and get in LTS 5. Upgrade to 0.11 with the next LTS.

2. Update to 0.11 now and then bug the Stackage people into doing LTS 6 with Aeson 0.11.

Opinions? Thoughts?

/cc @MichaelXavier @MHova

**Comment by MHova** [comment]
Either way works for my particular needs. It would seem like 1 is easier/faster?

**Comment by bitemyapp** [comment]
@MHova 1 is not easier or faster and we'd get the benefit of the nicer error messages >=0.10 if we did number two.

**Comment by MHova** [comment]
Alright then 2 it is!

**Comment by bitemyapp** [comment]
@MHova well, being compatible with the current Stackage LTS is no small thing. Do you use Stack?

**Comment by MHova** [comment]
We are making changes to our build infrastructure to make Stack possible, but we're not dependent on it yet. We are still using regular old cabal and Hackage.

**Comment by crough** [comment]
0.11 is probably less work in the long term for y'all, so I would just go with that. 0.9 would be nice, but that too will be outdated soon and hopefully moving forward with the API isn't as painful as moving backward.

**Comment by mightybyte** [comment]
Since 0.9 and 0.11 are supposed to have the same behavior, could you do a new release with this constraint?

    aeson (>= 0.9 && < 0.10) || (>= 0.11 && < 0.12)

It seems like this should get the best of both worlds since 0.10 is marked as deprecated now.  If there's some obstacle to doing that, then I vote for just moving to 0.11.  It seems like 0.9 people should be able work around it simply by adding a line to extra-deps in their stack.yaml.

**Comment by mightybyte** [comment]
FWIW I was able to build bloodhound-0.8.0.0 with aeson-0.11.0.0 successfully.  You can see the exact state of what I was building here.

https://github.com/vfiles/bloodhound/tree/0.8-stable

**Comment by bitemyapp** [comment]
@mightybyte I've got a version going for this, currently getting errors about a ToJSON instance for NonEmpty. I need to finish the NonEmpty PR for Aeson before we can move forward.

**Comment by fizruk** [comment]
@bitemyapp are you planning on a release with a relaxed `aeson` bounds (like @mightybyte suggested)?
I am currently trying to bring `bloodhound` into my project, but very specific `aeson` version brings me much trouble.

**Comment by pavelkogan** [comment]
+1

It would be nice to be able to easily use latest `bloodhound` with Stackage LTS.

**Comment by mightybyte** [comment]
It looks like bloodhound-0.11.0.0 uses some features released in aeson-0.11.1.  So my guess is that you won't be able to use this version until stackage catches up and uses aeson-0.11.1 or greater.  Stackage LTS is always going to be inherently slower to adopt these new things.  Other options would be to add the newer version of aeson and bloodhound to extra-deps or just use cabal and let it handle dependency resolution for you.
