### ISSUE TITLE
Bump versions on semigroups and http-types in 0.8

### ISSUE THREAD

**Issue by mightybyte** [bitemyapp/bloodhound#110]
Any chance you could bump the versions on semigroups and http-types for bloodhound-0.8.0.0 in hackage?  Because of the aeson-0.10 mess we've decided not to upgrade aeson yet.  This can be done with a simple package metadata edit on hackage, so I decided not to bring this up with a pull request.  I can verify that bloodhound-0.8.0.0 does indeed build successfully with semigroups-0.18.0.1 and http-types-0.9.

**Comment by andrewthad** [comment]
I would like this change as well.

**Comment by andrewthad** [comment]
In the event that this doesn't get taken care of, I've have a [branch that bumps the bounds](https://github.com/andrewthad/bloodhound/tree/old_aeson_branch). For anyone who uses stack, you can add this to `stack.yml`:

    - location:
        git:    'https://github.com/andrewthad/bloodhound'
        commit: 'f3cc30a342d80035afec1dca13aaacebb107e527'
      extra-dep: true

**Comment by bitemyapp** [comment]
@andrewthad @mightybyte PR it and I'll cut a release.

**Comment by andrewthad** [comment]
What branch do I PR against? The only way I was able to figure out how far to roll back was that you had [tagged the 0.8.0.0 release](https://github.com/bitemyapp/bloodhound/releases/tag/v0.8.0.0), so I checked out the 7b0c8012e1fec6ef019585c5de9a86b25bb3f7f5 commit rather than any particular branch.

**Comment by bitemyapp** [comment]
Oh wait, sorry, this is still 0.8 stuff. Nevermind. Continue with the vendored version. We're waiting for people to catch up to the new Aeson.
