### ISSUE TITLE
doco appears to be wrong for advanceScrollId

### ISSUE THREAD

**Issue by mwotton** [bitemyapp/bloodhound#113]
afaict, a scrollId will always be returned (at least in elasticsearch 2.1.1) - signalling appears to be done by having an empty list of hits.

**Comment by MHova** [comment]
The docs are indeed wrong! I pointed this out [previously] (https://github.com/bitemyapp/bloodhound/issues/95) and provided a [fix] (https://github.com/bitemyapp/bloodhound/pull/96). The fix is in master, but hasn't been released yet.

**Comment by mwotton** [comment]
Oops, my apologies :)

**Comment by bitemyapp** [comment]
@MHova should be released now, 0.11.0.0 was `Thu Mar 3 18:32:31 UTC 2016 by bitemyapp`

**Comment by MHova** [comment]
Ah great!

**Comment by bitemyapp** [comment]
Closing this unless someone says current docs aren't right.
