### ISSUE TITLE
The first example in the docs doesn't work without the OverloadedStrings extension 

### ISSUE THREAD

**Issue by dinnu93** [bitemyapp/bloodhound#129]
The first example in the docs doesn't work without the OverloadedStrings extension. It keeps saying that the Server expects it's argument to be of type Text.

**Comment by bitemyapp** [comment]
@dinnu93 Think it got changed during the `String` purge. Sounds like a great PR for a first-timer!

**Comment by bitemyapp** [comment]
Cheers :)

**Comment by dinnu93** [comment]
Thank you for the merge ! This is my first time. Looking forward to contribute more :) One doubt though, Why did my travis build test failed ?

**Comment by bitemyapp** [comment]
@dinnu93 my fault, I was in the middle of breaking master branch, which I shouldn't have done. That's why I merged anyway.
