### ISSUE TITLE
How to add Regexp queries it doesn't have a mkRegexpQuery

### ISSUE THREAD

**Issue by dinnu93** [bitemyapp/bloodhound#136]
How to add Regexp queries it doesn't have a mkRegexpQuery, What flags and boost to set for default use case like the below link

[https://www.elastic.co/guide/en/elasticsearch/guide/2.x/_wildcard_and_regexp_queries.html](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/_wildcard_and_regexp_queries.html)

**Comment by bitemyapp** [comment]
Your URL is broken and I'm not sure what this issue is meant to accomplish. What's up?

**Comment by dinnu93** [comment]
Sorry my bad click the url now

**Comment by bitemyapp** [comment]
http://hackage.haskell.org/package/bloodhound-0.11.0.0/docs/Database-Bloodhound-Types.html#t:RegexpQuery

You should be able to construct it like a regular value.

**Comment by dinnu93** [comment]
Yeah but what values do I set for flags and boost for default behaviour

**Comment by bitemyapp** [comment]
`NoRegexpFlags` and `Nothing` for Boost I'd think. I don't think there's an actual issue here, so I'm closing this issue.
