### ISSUE TITLE
Run more quickcheck tests in CI

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#160]
This will make our test runs longer but we keep getting periodic test failures where quickcheck correctly identifies a failure that isn't caught on the next run. I think the quickcheck test number by default is pretty small so we should bump it up to at least catch these errors more often and hopefully stamp them out.

**Comment by bitemyapp** [comment]
I care more about being able to trust the CI, myself.

**Comment by MichaelXavier** [comment]
Done.
