### ISSUE TITLE
Aeson 1.1 compatibility

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#162]
https://github.com/fpco/stackage/issues/2177

Ahoy mateys.

/cc @bermanjosh @MichaelXavier 

Mind if I work towards compat on this? https://github.com/bitemyapp/bloodhound/pull/158 still has merge conflicts, should I push forward separately?

**Comment by bermanjosh** [comment]
Yeah, of course not. I'll rebase when you're done - but once we're on it. Are those conflicts on #158 things you want me working on? Sorry if I misunderstood, I thought that was stuff that needed to be done someone with write access.

**Comment by bitemyapp** [comment]
@bermanjosh  I'm not sure I understand. It's your PR from your fork on your es5 branch. You can reconcile it with master on your local copy, push to your fork's es5 branch, and the PR will update. Have I missed something?

It sounds like I have the thumbs up from you to push forward with a release for Aeson 1.1 compat otherwise? I wanted feedback because Aeson is a touchy one.

**Comment by bermanjosh** [comment]
@bitemyapp No, you didn't miss anything, **I** did. Sorry. I'll do that tomorrow. 

As for the Aeson, yeah, go for it, don't let me hold you back. I'll take whatever you do and push it into my fork as well when you're done.

**Comment by bitemyapp** [comment]
Well, it's not just about your fork. I think Aeson will avoid breakage going forward but I'm a bit touchy about updating it after the `0.10` debacle.

**Comment by bermanjosh** [comment]
@bitemyapp In theory I'd say better to wait a week and see if anything evil happens, but I don't think it's worth falling behind. What's the time limit for stackage?

**Comment by MichaelXavier** [comment]
Anything I can help on with this? I'm getting pinged via the aeson1.1 mega ticket [here](https://github.com/fpco/stackage/issues/2177) that several of my libraries need an upgrade. Bloodhound dep in katip-elasticsearch is tripping me up. The changelog for 1.1 looks pretty innocuous.

**Comment by bitemyapp** [comment]
@MichaelXavier still at conf and won't be home and able to work until like Saturday. If you'd like it done before then, I certainly wouldn't discourage you cutting a release yourself before we resolve the new split modules stuff.

Otherwise, I have to imagine I'll have time for it in the coming weekend.

**Comment by MichaelXavier** [comment]
And we're green! Should I go ahead and go from `0.12.0.0` -> `0.12.1.0` and publish?

**Comment by bitemyapp** [comment]
@MichaelXavier I had one question on the merged PR, but other than that, yes I believe so.

**Comment by MichaelXavier** [comment]
Published this a while ago.
