### ISSUE TITLE
Merge of ES5 branch (V1/V5 modules) errored in TravisCI

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#166]
![screenshot from 2017-01-19 13-20-14](https://cloud.githubusercontent.com/assets/320177/22121513/0bc57300-de4a-11e6-8253-e5923bdc0adf.png)

/cc @bermanjosh

**Comment by bermanjosh** [comment]
@bitemyapp 
The error seems to be a timeout: `The job exceeded the maximum time limit for jobs, and has been terminated.` 

@MichaelXavier Maybe jumping 20x tests was too much? Can we give 500 a try?

**Comment by MichaelXavier** [comment]
@bermanjosh go for it. The output stops at a quickcheck counter so it seems like that is the case.

**Comment by bermanjosh** [comment]
@MichaelXavier I can't do it directly. @bitemyapp Do you want a PR or to do it yourself?

**Comment by bitemyapp** [comment]
@bermanjosh PR

**Comment by MichaelXavier** [comment]
Is this resolved?

**Comment by bitemyapp** [comment]
@MichaelXavier yep good call, thanks.
