### ISSUE TITLE
aeson 1.2 compatibility

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#180]
per https://github.com/fpco/stackage/issues/2449

**Comment by 23Skidoo** [comment]
`cabal new-build --enable-test --allow-newer=aeson` [completes successfully](https://gist.github.com/23Skidoo/e08bbcd8ff02a7d3ee7ef1f74a90d9fc) with 0.12.1.0, so it'd be nice if you could bump the Hackage upper bound on `aeson` for that version as well.

**Comment by bitemyapp** [comment]
@23Skidoo No, mutating previously released packages is bad. You don't have my consent to edit it either.

**Comment by bitemyapp** [comment]
This is fixed with the release of `0.14.0.0`.
