### ISSUE TITLE
Consider workaround for stalled builds

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#194]
I just dealt with this in a project that depends on bloodhound. I think because the bloodhound package itself take so long to compile, combined with the probably pretty slow hardware on travis free, we often stall out because there's no output after 10 minutes. I added the following to my project's `install` stanza in `.travis.yaml`: `- while true; do echo "travis pls"; sleep 30; done &` and it worked. I figured I'd ask here before doing something so ridiculous on this project.

**Comment by bitemyapp** [comment]
I think this is fixed now. All hail `stack build --fast` and 10gb of TravisCI cache.
