### ISSUE TITLE
listIndices doesn't work when you have closed indices

### ISSUE THREAD

**Issue by andrewthad** [bitemyapp/bloodhound#220]

**Comment by MichaelXavier** [comment]
Could you please provide some more detail?

**Comment by andrewthad** [comment]
Here's an example of some of my indices as outputted by `/_cat/indices`:

```
green open  rec-14-58108-shrunk         Zo78SIEwQlaZZ4eN-OGXYQ 1 1   1829198 0    5.1gb    2.5gb
      close rec-9-58105                 P74WGOX7ReGdQ1Lv94Ebkw                                  
      close rec-19-58107                c5LA8q5oSn6eGGOPMnpUOw                                  
green open  rec-18-58132                D3JTzTEtSNizN8m9Uf1aiQ 8 0  12590246 0    4.1gb    4.1gb
      close rec-19-58098                K9b825lrQYiQ85jT1IwM8w                                  
green open  rec-1-58109                 7L0xI23MTFCoklY2RDCl6g 8 1  87335940 0  227.7gb  113.8gb
green open  rec-19-58121                6d3AeqXtQG-nTYpiToT_VQ 8 0  14511937 0    3.8gb    3.8gb
```

Notice that the closed ones are missing the red/yellow/green status. This causes bloodhound to pick up the uuid as the index name. Ideally, I think the closed ones should just be omitted since they are basically unusable. Or maybe a separate function named `listOpenIndices` should be added for that purpose.

**Comment by MichaelXavier** [comment]
@andrewthad thanks! @bitemyapp how do you feel about `listIndices` returning closed index names vs omitting them? I imagine this should be an easy fix and I could take a crack at it.

**Comment by bitemyapp** [comment]
@MichaelXavier I don't have strong opinions but omitting them seems wrong as `listIndices` doesn't really specify "open only" and closed indices are mentioned in the listing, just listed in a different way.

**Comment by MichaelXavier** [comment]
I've fixed this in master.

**Comment by bitemyapp** [comment]
@MichaelXavier thank you!
