### ISSUE TITLE
No way of using default shard- and replica counts for indexes

### ISSUE THREAD

**Issue by bugthunk** [bitemyapp/bloodhound#227]
I'm curious why there is no way of specifying that an index should be created using the default number of shards and replicas defined on the index. This means that these settings are always controlled from the client end. Is this a conscious design decision, or are there some particular difficulties associated with such functionality?

**Comment by bitemyapp** [comment]
It's not particular to shard and replica counts, you shouldn't rely on Elasticsearch's defaults. They affect operational decisions too. The availability and consistency tradeoffs are something you have to think about and test against your expected workload. Similarly, I _strongly_ recommend specifying a proper mapping type.

Elasticsearch likes to lose data, protect ya neck.

**Comment by andrewthad** [comment]
I agree with the sentiment that relying on the ElasticSearch default here would be bad. The defaults for shard and replica count are almost never appropriate.

**Comment by bugthunk** [comment]
I disagree strongly. The defaults can be controlled by an admin that does not in fact have access to updating source code. If you do not want to rely on ES defaults, you can always create client side code that in fact enforces this for *you* - as you're doing it now, you're taking away one fine feature from your whole user base. But do what thou wilt.

**Comment by bitemyapp** [comment]
@bugthunk I think it's reasonable to want ops to be responsible for this but then why is the application setting the index shard and replica settings at all?

**Comment by bugthunk** [comment]
"Are you thinking of something like<...>?": Yes. I should have used the word templates in there somewhere. Mea culpa.

If I could tell how to not send in replica and shard counts using `bloodhound`, I would. Even `createIndexWith` needs a specified shard count.

**Comment by bugthunk** [comment]
Sorry for the late response. I'm a misfit.
