### ISSUE TITLE
Is it possible to consider using bloodhound for Elasticsearch v6?

### ISSUE THREAD

**Issue by arnauorriols** [bitemyapp/bloodhound#228]
Before I start playing with it and find out by myself, maybe somebody can already tell me what are the chances of being able to use bloodhound-v5 against ES v6 (I imagine they are close to none)?

**Comment by andrewthad** [comment]
I’ve been using it with version six  for about two months. It works fine. Remember that v6 only allows you to define one mapping per index. That was the biggest breaking change for me.

**Comment by arnauorriols** [comment]
Great to know. I'll give it a go then. 

Thanks.

**Comment by MichaelXavier** [comment]
I wonder if there's a way without cloning the entire tree to indicate that 6 is compatible via V5.

**Comment by bitemyapp** [comment]
@MichaelXavier `mkdir -p Database/V6/`, add a `Database.V6.Bloodhound` module that re-exports V5?
