### ISSUE TITLE
Support aeson-1.3

### ISSUE THREAD

**Issue by 23Skidoo** [bitemyapp/bloodhound#229]
`bloodhound` seems to work fine with the `aeson` dependency relaxed to `< 1.4`, so it'd be nice to see a new minor release or a Hackage revision adding support for that version.

**Comment by MichaelXavier** [comment]
@bitemyapp any objection to me releasing a minor version? This would help me unblock katip-elasticsearch on stackage.

**Comment by 23Skidoo** [comment]
BTW, the latest `aeson` is now 1.4.0.0.

**Comment by bitemyapp** [comment]
@23Skidoo I've asked for Hackage revisions to not be applied to packages I maintain.

@MichaelXavier by all means, but this is 0.16 due to the module reorg. Are you trying to cherry-pick changes for a minor version fix-up or should we just cut 0.16?

**Comment by MichaelXavier** [comment]
@bitemyapp are we pretty much ready to release the reorg? I'm personally fine with this bounds change just going into the reorg. The alternative is to reach back into the past and add it there. I personally like the idea of just ripping the bandage off the reorg and not doing a bunch of backporting. Everyone's time is limited, no need to make maintainership more burdensome than it is already.

**Comment by bitemyapp** [comment]
@MichaelXavier I agree 100%. I don't think there's a problem cutting a release of the reorg. If we change something that requires a major version bump later, so be it.

**Comment by MichaelXavier** [comment]
I've released 0.16.0.0. Working on getting it back into stackage but there are 2 test dependencies that have never been in stackage. I'll give their respective authors a bit of time to respond, but I think we could still probably get it back in stackage with tests disabled.

**Comment by blackheaven** [comment]
aeson 2 is supported, I close this issue
