### ISSUE TITLE
All requests should take Manager as an argument instead of creating a fresh one each time

### ISSUE THREAD

**Issue by ozataman** [bitemyapp/bloodhound#26]
Creating a fresh manager each time is not appropriate in production. Sharing a single Manager, supplied by the API user, for all operations:

- Gives the user control over the various arguments in creating Manager (TLS settings, pooling, etc.)
- Reuses connections to same server, avoiding lots of overhead
- Limits number of concurrent queries inherently to the total count of connections allowed
- Preserves/limits FDs used - too many concurrent requests can deplete them otherwise

**Comment by MichaelXavier** [comment]
I'd be willing to take this on. `withManager` is only used in two places. @bitemyapp I was thinking of wrapping up common running state (Server, Manager) in a type and doing something like something like `newtype BloodhoundM m a = BloodhoundM { unBloodhoundM :: ReaderT Config m a }`, and constraining `m` to `MonadIO` in the  operations. Alternatively we could continue with `IO` and just replace the first argument of all these functions with `Config`. Let me know what you prefer. Also let me know what you think of the name `Config` because it doesn't sit quite  right with me.

**Comment by bitemyapp** [comment]
@MichaelXavier I can't think of anything better than `Config` at the moment, renaming and wrapping it up into a product type is a good idea. `MonadIO m => m` is fine.

I've got some code (unrelated to this) I need to clean up before I can push a Hackage release, but if you put something together for this it'll put my butt in gear.

**Comment by ozataman** [comment]
You may want to consider a MonadBloodhound typeclass (MonadBH for short?) instead of a concrete monad. This helps with compatibility in more contexts. The full power of a ReaderT is probably too strong. This is the trick we play in cassy (see below) with MonadCassandra. You can then add the concrete BloodhoundM newtype (similar to Cas) for an easy and default stack.

http://hackage.haskell.org/package/cassy-0.7.1/docs/Database-Cassandra-Marshall.html

**Comment by bitemyapp** [comment]
A more unique name than `Config` would be good. Maybe something like `Bloodhound` or `BloodhoundConfig`?

**Comment by ozataman** [comment]
I agree; something less common would be better (to avoid name clashes). Also, to me, this is more of an environment than a config object. How about one of these:

`BHEnv` or `BhEnv`
`BloodhoundEnv`

Another decision point is whether to hide the `ResourceT` or expose it in the signature of the actions. I'm guessing the current internal combinators `runResourceT` to get rid of it. To me, the right thing is to leave it there so the user can decide if they want to embed these calls in larger ResourceT regions.

**Comment by MichaelXavier** [comment]
I've got a first stab up on the 26-bhenv branch. I figure I should add something like withTestEnv in the test suite to the client to provide a reasonable default for the case where you don't have a manager already.

Unit tests are passing. Haven't updated the doctests yet. I figure it should go through a round of review before going down that tedious route.

**Comment by MichaelXavier** [comment]
Also I think the latest http-client doesn't expose a `ResourceT` interface. It seems to have a much lower level io-based stream interface if you want it.

**Comment by bitemyapp** [comment]
@MichaelXavier it seems like http-conduit has MonadResource and ResourceT. Should bloodhound get flipped over to the higher level library?

**Comment by MichaelXavier** [comment]
@bitemyapp @ozataman  and I discussed this and we don't really gain much from going with http-conduit here. The main use case would be if bloodhound wanted good support for response bodies that need to be streamed and shouldn't be fit in memory. I'm not sure how common that is in practice but it would be tricky to support without a drastic API change.

I'm going to move forward with what I have here and put it up for review. I'd recommend we keep this in a branch off of master as there are several other slightly API breaking changes I'd like to propose and I don't want to interfere with regular released. If we end up using this in production we can test out this branch in the field before merging.

**Comment by MichaelXavier** [comment]
This branch is ready for review now and the tests are passing. Let me know what you guys think.

**Comment by bitemyapp** [comment]
@MichaelXavier should I see a PR? Not sure where I'm supposed to take a look, sorry.

**Comment by MichaelXavier** [comment]
Sorry, here you go https://github.com/bitemyapp/bloodhound/pull/27
