### ISSUE TITLE
Not possible to build with http-client >= 0.7

### ISSUE THREAD

**Issue by sternenseemann** [bitemyapp/bloodhound#288]
The `Eq` instance for `Response` has been removed: https://github.com/snoyberg/http-client/pull/435

Bounds should be adjusted on Hackage / a fix released ideally.

**Comment by sternenseemann** [comment]
Ah, I see eef1b58f033acf4a440b91dbfbfe931a105671be.

**Comment by blackheaven** [comment]
Sorry for the instability, I didn't checked with modern stack snapshot, I have to setup CI
