### ISSUE TITLE
Add example that deserializes response from ES

### ISSUE THREAD

**Issue by nsadeh** [bitemyapp/bloodhound#289]
I am new to Haskell and Bloodhound so maybe I just can't put 2+2 together as well as anyone else, but the sole example and documentation for searching ES seems to be printing the output to screen. It would be awesome to get an example where that response is actually deserialized.

**Comment by blackheaven** [comment]
I add it in 78b18d8db764e8411c8000e31f9ba7316ef42995

Let me know if it's clear enough, or if you have any idea to improve it.

**Comment by nsadeh** [comment]
Thank you!!
