### ISSUE TITLE
Score is nullable

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#30]
It turns out that at least in maxScore and hitScore in a result set, score can be null. Right now you represent that as a type alias for Double, but when the library parses it, it parses to NaN. I'm guessing the docs aren't that clear on the nullability so it may be appropriate to just universally update  the type of Score.

**Comment by bitemyapp** [comment]
Nuts. I'd rather fix the type than just have a note in the docs to the effect of, "btw this can ruin your day".

So I understand:

https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L1058-L1071

Does changing `Score` from `Double` to `Maybe Double` resolve this in your opinion?

**Comment by MichaelXavier** [comment]
Yeah I think that should do it. The FromJSON instances there should combine to do the right thing. Frankly, I'm kind of surprised the FromJSON instance worked on null in the first place without the Maybe :)

**Comment by bitemyapp** [comment]
I'm not surprised after the fact but I am a bit annoyed the JSON library takes advantage of an inhabitant that I ordinarily think of as being reserved for numerical work. :|
