### ISSUE TITLE
Requirements for next release

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#36]
Just wanted to check in and see if we were waiting on any more issues in preparation of the next release. If there are any, I'd like to get a definitive list so we can get those knocked out and ship. Thanks!

**Comment by bitemyapp** [comment]
@MichaelXavier presently, build errors: https://github.com/bitemyapp/bloodhound/pull/35

If I can figure that out, it'll go out for release.

**Comment by bitemyapp** [comment]
@MichaelXavier dunzokopf. If nothing goes wrong I'll push out in a bit tonight. Hopefully nothing goes wrong :worried:

**Comment by bitemyapp** [comment]
@MichaelXavier other than the doc builder at Hackage being stuck, [it's up](http://hackage.haskell.org/package/bloodhound). Hopefully everything is otherwise in order on our end.
