### ISSUE TITLE
Optimistic Concurrency Control on Writes

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#44]
https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html

It turns out ES has support for sending the version number of a retrieved record when you're doing a write as a concurrency control mechanism. It looks like this feature came around in 0.15. There's a few issues to hammer out. I'll post them here. I'll probably take a first stab on our fork since we need this feature sooner rather than later, but I'll happily update the solution if there's a more appropriate one for bloodhound proper.

## Version Types
There seem to be 4 types of concurrency directives when [indexing a document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning): 

1. `internal`. You're using the versioning scheme ES establishes
2. `external/external_gt`. Docs imply these are the same, you provide
   your own version as a non-negative long number and the write
   succeeds if the version has incremented or there's no doc. This
   means that every single write must increment this number, which is
   different than internal which expects the version value to stay the
   same and will auto-increment if its not provided.
3. `external_gte` This is pretty much internal with your own version
   numbers.
4. `force` No conflict checking is done. Take the value supplied and
   use that as the new current version.

So we'd probably have a sum type `VersionType` that covers these cases

I definitely want to create a newtype `Version` with a smart
constructor and `Bounded` instances to bake in this positive number
invariant.

I am also considering adding a newtype over `Version` named `ExternalVersion`
and using that type in the external constructors of `VersionType`,
that way in user code you need to explicitly construct an external
version. When you get a result back from the server, it will be a
plain `Version`, since ES won't really tell us the disposition of a version.

## New function or modify existing
I started leaning towards adding an `indexDocumentVersioned` but I
think this is a mistake because there are other knobs on indexing
(e.g. [operation type](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type))
that we'll probably need to support some day.

Instead I advocate for adding an `IndexDocumentSettings` type and a
`defaultIndexDocumentSettings` value. Version type would be mandatory
and default to internal. Supplying a version will be optional. This
will let us only have to rip the band-aid of changing function arity
once.

## Handling conflicts
This part is still murky to me. I'm not actually sure what the driver
does right now when you get an error. It looks like you get a
`VersionConflictEngineException` error if there's a versioning
issue. The user is at the very least going to need documentation of
how to catch this case, as they'll likely want to re-read and retry.

**Comment by bitemyapp** [comment]
Your design for `Version` sounds good to me.

I agree `IndexDocumentSettings` rather than a separate function is probably the way to go.

For handling conflicts, we're talking about either a proper error or exception. Documentation on how to catch it is probably sufficient. Is it worth trying to parse out the new version number or is it mostly not going to matter and they just need to know it failed and to see the error body?

**Comment by MichaelXavier** [comment]
So I decided to actually try this out while writing tests for my change and I'm pretty sure ES is just putting some Java exception through a serializer. It would be awesome if we could parse out the exact version and stuff, but it looks like doing so would require us to parse an Error message which makes my skin crawl. For reference, here's the reply:

```haskell
Response {responseStatus = Status {statusCode = 409, statusMessage = "Conflict"}, responseVersion = HTTP/1.1, responseHeaders = [("Content-Type","application/json; charset=UTF-8"),("Content-Length","144")], responseBody = "{\"error\":\"V
ersionConflictEngineException[[bloodhound-tests-twitter-1][2] [tweet][1]: version conflict, current [1], provided [1]]\",\"status\":409}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
```

What would be a nice compromise though is I could look through the API conventions documentation and provide to start with:

```haskell
isVersionConflict :: Reply -> Bool
isVersionConflict = (== 409) . statusCode . responseStatus
```

With more to come later.

**Comment by MichaelXavier** [comment]
Pushed a commit that implements this. Added a simple test case that writes a value with a version control strategy that requires the value to increment, fails to increment it and asserts that the index is rejected with a version conflict. Have a look and let me know what you think.

**Comment by bitemyapp** [comment]
@MichaelXavier other than my comment about the query appending, your commit looks good to me. Good tests, thank you! :+1:

**Comment by bitemyapp** [comment]
I believe this is resolved and generally available now. Thank you @MichaelXavier ! :bear: :+1:
