### ISSUE TITLE
Incorrect mapping API is used

### ISSUE THREAD

**Issue by centromere** [bitemyapp/bloodhound#49]
According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-put-mapping.html), the proper URL to call when installing a mapping is `/INDEX/_mapping/MAPPING_NAME`. This is true for protocol versions 1.6, 1.5, 1.4, 1.3 and 1.2, which are tested for in `.travis.yml`. However, the URL being called by putMapping (et al.) is `/INDEX/MAPPING_NAME/_mapping`, which was last seen in protocol version 0.90.

This occurs for [putMapping](https://github.com/bitemyapp/bloodhound/blob/1db8ad7ca08ec619fd36a1945b0a1d714055def7/src/Database/Bloodhound/Client.hs#L315) and [deleteMapping](https://github.com/bitemyapp/bloodhound/blob/1db8ad7ca08ec619fd36a1945b0a1d714055def7/src/Database/Bloodhound/Client.hs#L329).

**Comment by bitemyapp** [comment]
A fix for this would be welcomed, preferably with a small test that will identify a regression.

**Comment by centromere** [comment]
The ES server accepts both the correct and incorrect form of the API calls (which is why the tests haven't failed so far), so it's not clear to me how to write such a test.

**Comment by bitemyapp** [comment]
@centromere that's disconcerting. Probably to avoid breaking compat then. A PR that fixes it and adds a comment noting why it has to be so will work for me then.
