### ISSUE TITLE
MonadMask / bracket

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/bloodhound#65]
Should BH have a MonadMask instance? What's the right thing to do here?

/cc @MichaelXavier

**Comment by MichaelXavier** [comment]
You may consider if it incurs additional dependencies. It may already indirectly require the package and if so, its not too big a deal IMO. You would probably just newtype derive an instance, right?

**Comment by mwotton** [comment]
this came up in the context of wanting to do bracket stuff inside the monad transformer stack. i ended up just using Control.Exception, but it's not a tremendously satisfying solution, as it means you have to do everything at the IO level.

**Comment by MichaelXavier** [comment]
PR is up for your perusal.

**Comment by bitemyapp** [comment]
Closed by #67
