### ISSUE TITLE
Update Index Settings

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#76]
I've hit a case where it would be useful to have this API so this is an issue do discuss the possible implementation. The documentation is refreshingly detailed about updating index settings:

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html

My first thoughts on a plan:
1. We can't use `IndexSettings`. The docs show a much more rich set of options that can be tweaked than `IndexSettings` provide.
2. You will get an error from the server if you provide an empty set of updates. Somewhere in the update type it should have a `NonEmpty IndexSettingsUpdate`.
3. `IndexSettingUpdate` would be a sum type over all the settings shown.
4. The type would then be something like `updateIndexSettings :: MonadBH m => NonEmpty IndexSettingUpdate -> IndexName -> m Reply`

Let me know what you think of the plan.

**Comment by bitemyapp** [comment]
@MichaelXavier zero things to object to in the proposal you've laid out here. Go for it!

One thing that caught me eye when I was reading the docs, the flipping around of index settings (refresh rate) for bulk indexing. Wondering how well that works and how dangerous it is. I need some AWS budget to play with :P
