### ISSUE TITLE
Add support for index aliases

### ISSUE THREAD

**Issue by MichaelXavier** [bitemyapp/bloodhound#79]
I'm knee deep in this one right now so this is a placeholder. This will add support for creating/updating index aliases as well as reading them back.

One thing important to note is this idea of adding these PUT/POST APIs and then adding the corresponding GET for testing and general use is that bloodhound may no longer get to punt on parsing the response. Most ops now are updates so they just return `m Reply`. For an API like say `getIndexAliases` whose sole purpose is to return a well-typed response, it seems unsatisfying to return an `m Reply` and hint in the docs that you should try parsing it as the right type.

The temporary approach I'm taking while working on this is to return `m (Either EsError TheThingYouExpect)`. It will try to parse the thing first and failing that, will parse an EsError. AFAIK all ElasticSearch errors conform to the EsError format, so misses on this should be rare. If it can parse neither, it throws a `StatusCodeException` from network client.

So perhaps mull over this approach and see what you think about it. It will also be relevant to that index settings ticket in #76. We'll probably use some subset of the index aliases feature in a Real App before I submit the PR.

**Comment by MichaelXavier** [comment]
The feature is basically done at this point but I have some cleanup and possibly some more thorough integration testing to do. I actually have Query/Filter and all the types they use with ToJSON/FromJSON instances now that are tested against eachother with quickcheck. This actually caused me to discover a few minor bugs with the JSON bloodhound is producing today. I've had to make some minor changes to types to squeeze out some ambiguous cases. Once I get this thing more polished we can discuss if these breaking type changes are worth it. They are all very simple to update and gravitate towards more precise types.

Now the weird part: I'm using stack and just recently the doctests will build but not run. It looks like its using 2 different versions of http-types in the doctests runtime and I don't know what even the fuck. Was hoping you may know what's going on @bitemyapp 

```
stack test   
bloodhound-0.9.0.0: unregistering (dependencies changed)
bloodhound-0.9.0.0: configure
Configuring bloodhound-0.9.0.0...
bloodhound-0.9.0.0: build
Preprocessing library bloodhound-0.9.0.0...
[1 of 4] Compiling Database.Bloodhound.Types.Class ( src/Database/Bloodhound/Types/Class.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Database/Bloodhound/Types/Class.o )
[2 of 4] Compiling Database.Bloodhound.Types ( src/Database/Bloodhound/Types.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Database/Bloodhound/Types.o )
[3 of 4] Compiling Database.Bloodhound.Client ( src/Database/Bloodhound/Client.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Database/Bloodhound/Client.o )
[4 of 4] Compiling Database.Bloodhound ( src/Database/Bloodhound.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Database/Bloodhound.o )
In-place registering bloodhound-0.9.0.0...
bloodhound-0.9.0.0: install
Installing library in
/home/michael/src/bloodhound/.stack-work/install/x86_64-linux/lts-3.10/7.10.2/lib/x86_64-linux-ghc-7.10.2/bloodhound-0.9.0.0-LY4jwk0WBAi30JAZDuqdxz
Registering bloodhound-0.9.0.0...
bloodhound-0.9.0.0: configure (test)
Configuring bloodhound-0.9.0.0...
bloodhound-0.9.0.0: build (test)
Preprocessing test suite 'doctests' for bloodhound-0.9.0.0...
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/doctests/doctests ...
Preprocessing library bloodhound-0.9.0.0...
In-place registering bloodhound-0.9.0.0...
Preprocessing test suite 'tests' for bloodhound-0.9.0.0...
[1 of 1] Compiling Main             ( tests/tests.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/tests/tests-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/tests/tests ...
bloodhound-0.9.0.0: test (suite: doctests)
Progress: 1/2
src/Database/Bloodhound/Client.hs:272:40:
    Couldn't match expected type ‘NHTS.Status’
                with actual type ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
    NB: ‘NHTS.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.9’
        ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.8.6’
    In the first argument of ‘NHTS.statusCode’, namely
      ‘(responseStatus resp)’
    In the first argument of ‘(==)’, namely
      ‘NHTS.statusCode (responseStatus resp)’

src/Database/Bloodhound/Client.hs:653:43:
    Couldn't match type ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
                   with ‘NHTS.Status’
    NB: ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.8.6’
        ‘NHTS.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.9’
    Expected type: Reply -> NHTS.Status
      Actual type: Response L.ByteString
                   -> http-types-0.8.6:Network.HTTP.Types.Status.Status
    In the second argument of ‘(.)’, namely ‘responseStatus’
    In the second argument of ‘(.)’, namely
      ‘NHTS.statusCode . responseStatus’
```

**Comment by bitemyapp** [comment]
@MichaelXavier I thought I fixed that, are you up to date with master?

re: breakages - I'm open to that based on how you've described what they're for.

Grateful you found problems and fixed 'em :)
