### ISSUE TITLE
FromJSON

### ISSUE THREAD

**Issue by dzhus** [bitemyapp/bloodhound#83]
Hello,

Under what circumstances would one want to use FromJSON instance for Queries?

**Comment by bitemyapp** [comment]
Being able to test isomorphism is nifty. I think @MichaelXavier hypothesized a use for it because there was a bit of Elasticsearch's API where they could return query results or something?

**Comment by MichaelXavier** [comment]
That's right. Its a real use case. When you create an index alias, you can attach a filter to it. One of the filter's constructors takes a query. I also added API support for reading a server's index aliases back, which would return the filter and thus the query it may have been configured with. Testing JSON isomorphisms are helpful but I only do them when both sides are used in exported code.

I hopefully should be able to free up some more time to finish with that changeset I've got baking pretty soon. I keep discovering new rabbit holes at the bottom of each rabbit hole.

**Comment by bitemyapp** [comment]
Closing this since I think the question has been answered. Reopen if something is unclear!

**Comment by dzhus** [comment]
Yes, thanks.
