### ISSUE TITLE
TermsResult cannot parse from numeric or boolean JSON

### ISSUE THREAD

**Issue by MHova** [bitemyapp/bloodhound#88]
Specifically because `termKey` is declared as type `Text`, non-String bucket terms like numbers and booleans will fail parsing.

We could either keep `termKey` as type `Text` and put some more smarts in `parseJSON` or introduce more data constructors (`TextTermsResult`, `NumericTermsResult`, etc) and also put some more smarts in `parseJSON`.

**Comment by bitemyapp** [comment]
@MHova I'd just as soon fix the type to be explicit about the possibility of Text, Bool, Number.

/cc @MichaelXavier

**Comment by MHova** [comment]
Thanks for the quick response. Let me take a stab at fixing this.
