### ISSUE TITLE
Restore bloodhound to stackage

### ISSUE THREAD

**Issue by DanBurton** [bitemyapp/bloodhound#92]
Please release a version of bloodhound that simultaneously supports `aeson-0.9.0.1`, `http-types-0.9`, and `semigroups-0.18.0.1` in order to be restored to Stackage. Even if lts-5.0 is released without bloodhound, we can get it into lts-5.1 or later, as soon as a compatible version is released.

See: https://github.com/fpco/stackage/issues/1155

**Comment by bitemyapp** [comment]
@DanBurton Bloodhound is back on Stackage with Aeson 0.11 right? Can we close this?

**Comment by DanBurton** [comment]
Sure.

Although bloodhound is included in the latest LTS builds, it seems to have been excluded from the nightlies. I've re-enabled it for those as well. https://github.com/fpco/stackage/commit/cfb31f06ad990fdcba78a75d892cac308cdcebf7

**Comment by bitemyapp** [comment]
@DanBurton thank you :)

**Comment by flip111** [comment]
Could V5 be added to stackage?

**Comment by MichaelXavier** [comment]
@flip111 it is. Latest nightly shows version 0.13.0.0 https://www.stackage.org/nightly-2017-03-28/package/bloodhound-0.13.0.0

**Comment by flip111** [comment]
ah ok so just wait for the next LTS 👍
