### ISSUE TITLE
Don't use ESProtocolException for user-caused JSON parsing errors

### ISSUE THREAD

**Issue by MHova** [bitemyapp/bloodhound#97]
The [docs](https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L565) around `ESProtocolException` direct the user to write a bug in the issue tracker if this error is ever encountered because it is indicative of an incompatibility between Bloodhound and ElasticSearch.

Well, that's not always the case. Speaking purely hypothetically of course, if _somebody_ were to screw up their own JSON domain object mapping causing `SearchResult.searchHits.hits` to not parse, an `ESProtocolException` will be thrown despite the fact that the Bloodhound library is fine.

Would it be a good idea (or even possible) to throw a different kind of Exception in this case and reserve `ESProtocolException` for things that are truly wrong with the library?

**Comment by bitemyapp** [comment]
>Would it be a good idea (or even possible) to throw a different kind of Exception in this case and reserve `ESProtocolException` for things that are truly wrong with the library?

/cc'ing @MichaelXavier - but my vote is yes.

**Comment by MichaelXavier** [comment]
I think it would be a good idea. I hadn't considered it. I think implementing this will be kind of weird. Bloodhound never returns the user's type directly, its always wrapped in some intermediate record, like `SearchHits`. The code that throws `ESProtocolException` is trying to parse a `SearchHits UserType`, and failing that, tries to parse an `EsError` and failing that as well throws an `EsProtocolException`. I think you'll have trouble differentiating between the user supplied parser producing the error and the bloodhound-supplied parser producing the error, which is the point of the protocol exception.

If you wanted to get crafty, you could parse every parameterized ElasticSearch type to first parse as, for instance `SearchHits Value`. If that failed, you could be sure its either an `EsError` or an `EsProtocolException`. You'd then send the value through one more trip through `parseJSON` to arrive at the final result. The problem with this approach is that I don't know how to do it in a way that doesn't force you to write a bunch of specialized versions. Its like you want 1 version to parse `FromJSON a => a` of kind `*` and one to parse `FromJSON f, FromJSON a => f a` where `f` is kind `*->*`. Maybe that's all you need, 2 functions to work on those two kinds ¯\_(ツ)_/¯

**Comment by MHova** [comment]
Perhaps just modifying the `ESProtocolException` docs to talk about this scenario would suffice?

**Comment by bitemyapp** [comment]
@MHova merged your PR, closing this issue on the assumption that his resolves it. Please let me know if this isn't true or something changes.

**Comment by MHova** [comment]
:+1:
