### ISSUE TITLE
Support Missing Aggregation

### ISSUE THREAD

**Issue by MHova** [bitemyapp/bloodhound#99]
Add support for the "Missing Aggregation", which has been available in ElasticSearch since [1.3](https://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-aggregations-bucket-missing-aggregation.html).

**Comment by MHova** [comment]
I'll issue a PR on this.

**Comment by bitemyapp** [comment]
@MHova >available in ElasticSearch since 1.3.

1.2.4 is definitely getting deprecated then :stuck_out_tongue:

**Comment by MHova** [comment]
Ha maybe? 1.2.4 may or may not have actually supported this, but >=1.0 && <1.3 docs are no longer available on the ElasticSearch website.

**Comment by bitemyapp** [comment]
@MHova oh nuts. We should deprecate it anyway if they aren't going to make the bloody docs available. Yeesh.

**Comment by MHova** [comment]
Yeah that's a good idea. For some reason, the 0.9 docs are still available though.
